{% set version = "0.3.1" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-furrr
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/furrr_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/furrr/furrr_{{ version }}.tar.gz
  sha256: 0d91735e2e9be759b1ab148d115c2c7429b79740514778828e5dab631dc0e48b

build:
  merge_build_host: true  # [win]
  number: 1
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-ellipsis
    - r-future >=1.19.1
    - r-globals >=0.13.1
    - r-lifecycle >=0.2.0
    - r-purrr >=0.3.0
    - r-rlang >=0.3.0
    - r-vctrs >=0.3.2
  run:
    - r-base
    - r-ellipsis
    - r-future >=1.19.1
    - r-globals >=0.13.1
    - r-lifecycle >=0.2.0
    - r-purrr >=0.3.0
    - r-rlang >=0.3.0
    - r-vctrs >=0.3.2

test:
  commands:
    - $R -e "library('furrr')"           # [not win]
    - "\"%R%\" -e \"library('furrr')\""  # [win]

about:
  home: https://github.com/DavisVaughan/furrr
  license: MIT
  summary: Implementations of the family of map() functions from 'purrr' that can be resolved using any 'future'-supported backend, e.g. parallel on the local machine or distributed on a compute cluster.
  license_family: MIT
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/MIT

extra:
  recipe-maintainers:
    - conda-forge/r
